apiVersion: v1
kind: Service
metadata:
  name: streaming
  labels:
    app: streaming
spec:
  type: ClusterIP
  ports:
    - name: hls
      port: 6060
      targetPort: 6060
    - name: rtmp 
      port: 1935
      targetPort: 1935
    - name: stream-logic 
      port: 1339
      targetPort: 1339
    - name: love-db
      port: 55994
    - name: login
      port: 8021
    - name: comments
      port: 8080
    - name: chat
      port: 9876

  selector:
    app: streaming
